### PR TITLE
Update Head.tsx

### PR DESCRIPTION
**Pull request by Budalebah**
correction of twitter name

### CODE REVIEW

**Comment by danielmarinq** [comment]
Thanks! Wondering if it needs to be "@NexusLabsHQ" or "NexusLabsHQ". @nexodon can you take a look?

**Comment by Budalebah** [comment]
yes maybe i should add twitter:title without @ but twitter site with @ , let me fix

**Comment by Budalebah** [comment]
Can you check ser?

**Review by nexodon — APPROVED** [review]
lgtm - thank you for your attention to detail and for clarifying!

**Comment by Budalebah** [comment]
Can you merge this to be closed, thanks a lot. Happy to be part of this community!

**Pull request merged**
