### PR TITLE
Fix Runtime Bugs

### PR DESCRIPTION
**Pull request by sjudson**
Bugs introduced in https://github.com/nexus-xyz/nexus-zkvm/pull/208. @yoichi-nexus do you know why that PR cleared CI/CD?

### CODE REVIEW

**Review by yoichi-nexus — APPROVED** [review]
looks good

**Comment by yoichi-nexus** [comment]
> do you know why that PR cleared CI/CD?

no, my suspicion is it's pulling source from github at some point instead of using the current commit.

**Comment by sjudson** [comment]
> no, my suspicion is it's pulling source from github at some point instead of using the current commit.

That may cause this PR to fail CI/CD as well then...

**Comment by slumber** [comment]
Makes sense to add
```sh
cargo check -p example --target=riscv32i-unknown-none-elf
```
to CI.

**Pull request merged**
