### PR TITLE
examples: add simple palindrome checkers

### PR DESCRIPTION
**Pull request by arajasek**
This PR adds another simple example, this one checking whether strings and integers (both decimal and binary) are palindromes. 

I created this just to play with the prover, so feel free to merge if useful, or just close otherwise.

Sample output:

```
Executing program...
madam is a string palindrome
23432 is a decimal palindrome
33 is a binary palindrome
Executed 4080 instructions in 140.147812ms. 1607560 bytes used by trace.
  Loading public parameters ... 3.9s
 Finished in 3.9s
  Computing step 0 ... 852ms
.
.
.
Computing step 254 ... 985ms
Proved 255 step(s) in 4min5s; 16.62 instructions / second
Saving proof ... 61ms
Finished in 61ms
```

### CODE REVIEW

**Comment by danielmarinq** [comment]
Nice example! @sjudson is working on the examples / applications. 

Sam, can you take a look?

**Comment by arajasek** [comment]
> @arajasek this looks like a really nice example, as it tests a broad set of instructions for the VM. Thank you very much for it!
> 
> Any chance you might be able to add a few negative test examples as well? I'm also happy to do so myself, but appreciate your contribution and want to give you the opportunity to do so first.

You're welcome, I thought it'd be nice to get some bit manipulation in an example.

I'm happy to add some negative examples, will do so soon (afk rn).

**Comment by arajasek** [comment]
> @arajasek this looks like a really nice example, as it tests a broad set of instructions for the VM. Thank you very much for it!
> 
> Any chance you might be able to add a few negative test examples as well? I'm also happy to do so myself, but appreciate your contribution and want to give you the opportunity to do so first.

Added negative examples too!

**Comment by sjudson** [comment]
They look great, thanks again.

**Review by sjudson — APPROVED** [review]

**Pull request merged**
