### PR TITLE
Add tests proving and verifying the test machines

### PR DESCRIPTION
**Pull request by yoichi-nexus**
Closes https://github.com/nexus-xyz/nexus-zkvm/issues/218

### CODE REVIEW

**Review by sjudson — COMMENTED** [review]
Can we test Jolt as well? None of these test machines use ECALLs, I don't think.

**Comment by yoichi-nexus** [comment]
> Can we test Jolt as well? None of these test machines use ECALLs, I don't think.

Each of these is worth a follow-up issue, mainly due to the involved chores:
* [jolt](https://github.com/nexus-xyz/nexus-zkvm/issues/239): jolt VM needs a vector of ELFInstructions; the test machines contain u32's
* [ecall](https://github.com/nexus-xyz/nexus-zkvm/issues/240): trace_vm will take private inputs, each test machine should be equipped with a tape of private inputs

**Review by sjudson — APPROVED** [review]

**Review by slumber — APPROVED** [review]
nice, thanks!

**Comment by slumber** [comment]
> Can we test Jolt as well? None of these test machines use ECALLs, I don't think.

Jolt needs an actual elf for memory checking, so it's not compatible

**Pull request merged**
