### PR TITLE
chore: reorg cli crates for release

### PR DESCRIPTION
**Pull request by slumber**

### CODE REVIEW

**Comment by slumber** [comment]
This is a proposal mini-PR, what it does:
1. Rename `nexus-tui` to a more explicit `nexus-progress-bar` 
2. Rename `nexus-tools` to a more explicit `cargo-nexus` to avoid confusion with `nexus-sdk`. See https://crates.io/crates/cargo-make/ https://crates.io/crates/cargo-expand
3. Some high level docs

The docs on README and vercel are not updated because commands specify tags. Once we publish crates, it should be changed to
```sh
cargo install cargo-nexus
```

**Review by nexodon — APPROVED** [review]
Nice comments. Seems reasonable renaming. lgtm

**Review by sjudson — COMMENTED** [review]
This should also update the main readme + quickstart, right?

**Comment by slumber** [comment]
> This should also update the main readme + quickstart, right?

See https://github.com/nexus-xyz/nexus-zkvm/pull/222#issuecomment-2226896644

**Comment by sjudson** [comment]
> > This should also update the main readme + quickstart, right?
> 
> See [#222 (comment)](https://github.com/nexus-xyz/nexus-zkvm/pull/222#issuecomment-2226896644)

Ah, sorry, missed that. Approved

**Review by sjudson — APPROVED** [review]

**Pull request merged**
