### PR TITLE
Fix Cargo lock error

### PR DESCRIPTION
**Pull request by duc-nx**
Summary:

Test Plan:

### CODE REVIEW

**Comment by slumber** [comment]
Have you tested jolt?

**Comment by sjudson** [comment]
Following on from @slumber, let's stick with 1.77.0 for the time being: there may be a lot of edge cases to upgrading to 1.80.0, so let's just get the CI working and we can consider the upgrade later.

**Review by sjudson — CHANGES_REQUESTED** [review]
Following on from @slumber, let's stick with 1.77.0 for the time being: there may be a lot of edge cases to upgrading to 1.80.0, so let's just get the CI working and we can consider the upgrade later.

**Comment by sjudson** [comment]
Closing in preference of alternate approach.

**Pull request closed without merging**
